before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
env:
  - DB=sqlite
script:
  - "export DISPLAY=:99.0"
  - "alias set_gemfile='export BUNDLE_GEMFILE=\"`pwd`/Gemfile\"'"
  - "cd ../core; set_gemfile; bundle install --quiet; bundle exec rspec spec/models/order/callbacks_spec.rb"

notifications:
  email:
    - ryan@spreecommerce.com
branches:
  only:
    - debugging-order-callbacks
rvm:
  - 1.9.3
